timeout: 3

/MyOS
    protocol: limine
    resolution: 1280x720
    path: boot():/boot/kernel
    module_path: boot():/boot/shell.elf
    module_path: boot():/boot/hello.elf
    module_path: boot():/boot/demo.elf
    module_path: boot():/boot/threads.elf
