#!/bin/sh
# Generate kernel blob table from user/programs.mk PROGRAMS list.
# Usage: gen_user_embeds.sh shell hello > build/user_embeds_gen.c

set -e

cat <<'EOF'
/* Auto-generated by tools/gen_user_embeds.sh — do not edit. */
#include "user_embeds.h"

#include <stddef.h>
#include <stdint.h>

EOF

for prog in "$@"; do
    echo "extern uint8_t _binary_user_${prog}_elf_start[];"
    echo "extern uint8_t _binary_user_${prog}_elf_end[];"
    echo
done

echo "const struct user_embed user_embed_table[] = {"
for prog in "$@"; do
    cat <<EOF
    {
        "${prog}.elf",
        _binary_user_${prog}_elf_start,
        _binary_user_${prog}_elf_end,
    },
EOF
done
echo "};"
echo
echo "const size_t user_embed_count = sizeof(user_embed_table) / sizeof(user_embed_table[0]);"
echo
cat <<'EOF'
static int name_ends_with(const char *path, const char *suffix) {
    if (!path || !suffix) {
        return 0;
    }
    size_t plen = 0;
    size_t slen = 0;
    while (path[plen]) {
        plen++;
    }
    while (suffix[slen]) {
        slen++;
    }
    if (slen > plen) {
        return 0;
    }
    for (size_t i = 0; i < slen; i++) {
        if (path[plen - slen + i] != suffix[i]) {
            return 0;
        }
    }
    return 1;
}

const struct user_embed *user_embed_lookup(const char *name) {
    if (!name) {
        return NULL;
    }
    for (size_t i = 0; i < user_embed_count; i++) {
        if (name_ends_with(name, user_embed_table[i].name)) {
            return &user_embed_table[i];
        }
    }
    return NULL;
}

size_t user_embed_size(const struct user_embed *emb) {
    if (!emb || !emb->start || !emb->end || emb->end < emb->start) {
        return 0;
    }
    return (size_t)(emb->end - emb->start);
}
EOF
